### PR TITLE
Add option to select formula from a list of user formulas

### LINKED ISSUE #123: Allow selecting from a list of user formulas
This would be useful for new-comers to learn the syntax of user formulas, and also to provide more examples immediately. Also, the list could be saved for the next startup of XaoS as well. See http://rtzme.sourceforge.net/english.php for some idea how this could be implemented.

### PR DESCRIPTION
**Pull request by kanurag94**
Type: Enhancement
Fixes #123 

Added option to select formula from a list of user formulas.
1. New formulas can be saved using the ```Add``` button, cursor will automatically point to new formula once it is added.
2. Existing formulas can also be selected and deleted using the ```Delete``` button.
3. Click OK after selecting formula, to apply formula to the fractal.
4. Currently used formula is populated every time dialog box is opened automatically.

Where to find?
Fractal -> Saved user Formulas

Screenshot

Screenshot from 2020-08-17 23-17-02

Further Info:
DIALOG_ILIST type dialog can be reused to create such dialog boxes again. This will be helpful in multiple scenarios. Just put a check for ```label``` name and save the list there.

### CODE REVIEW

**Comment by kovzol** [comment]
I like the new feature, thanks for the improvement!
Maybe it would be even better if there was no new option for that, but this could be added to the menu User formula..., and an editable combobox could show the current formula, and a list of the former formulas could be shown when opening the list with the arrow icon. In this way there would be no option to remove a formula, but the interface would be more intuitive. Actually, if a user finds a nice formula, he/she will save it as an .xpf file. So there is no need to maintain a big database of formulas, only the last couple of entries should be shown for the user's convenience.

**Comment by kanurag94** [comment]
So something like this? with upto 10 historical data? and drop down list openable by arrow icon?
rsz_1drawing

**Comment by kovzol** [comment]
No, with only one input field. Similarly to the URL input field in most browsers.

**Comment by kanurag94** [comment]
Screenshot from 2020-08-19 16-32-17
Maybe this?

**Comment by kovzol** [comment]
Yes---I guess the input field is editable. ;-)

**Comment by kanurag94** [comment]
Updated #202  with the changed :D

**Pull request merged**
