### PR TITLE
French translation improvement

### PR DESCRIPTION
**Pull request by verdesroches**
Some improvement in the french translation file.

I may review the full french translation in the next few days.

### CODE REVIEW

**Comment by verdesroches** [comment]
I found some time tonight in order to finish translation. Seems to be OK for now ! You should pull this now !

**Comment by kovzol** [comment]
Thanks for the improvements! Unfortunately I found your work just now.

**Comment by cvermot** [comment]
> Thanks for the improvements! Unfortunately I found your work just now.

No problem ! It will be in the next release !!!

> Great, thank you! Please can you give us some information on your contact data? Your name should be added to the credits. (Eventually also your email address.)

I juste updated my profile to give these informations.

**Comment by kovzol** [comment]
Thanks! https://github.com/xaos-project/XaoS/commit/484f146fe1dd2449b4cb084c751c3712284ceadd

**Pull request merged**
