### PR TITLE
Russian translation and xdg fix

### PR DESCRIPTION
**Pull request by glixx**

### CODE REVIEW

**Comment by jblang** [comment]
Did you test that this was working?  I installed language-pack-ru-base and set LANG=ru_RU.UTF-8 and I am still seeing messages in English.

**Comment by glixx** [comment]
Will you try:
`LANGUAGE=ru xaos`

Yes, I tested. It has segfault on at least 2 strings: https://github.com/xaos-project/XaoS/issues/99 and encoding problem https://github.com/xaos-project/XaoS/issues/100 (there is my screenshot of test there)

**Comment by jblang** [comment]
Another thing that is missing from your translation is the catalog for the tutorials.  See [examples](https://github.com/xaos-project/XaoS/tree/master/catalogs) from other languages.

**Comment by glixx** [comment]
cat files are not standard. No way to translate them except text editor.
Will you convert them into Java properties utf8 format? This format can be translated by transifex.

**Pull request merged**
