### PR TITLE
Save xpf data in png chunk

### LINKED ISSUE #128: Save xpf data in png chunk
PNG supports arbitrary text chunks as user metadata.  We could save the xpf location data here and a user could reload a png generated from XaoS and continue zooming on it without the original xpf.

### PR DESCRIPTION
**Pull request by kanurag94**
Type : Enhancement
Fixes #128 

Changes:
Added option to 'Open Image' under File menu.T
This option allows to save & open PNG without XPF data.

### CODE REVIEW

**Comment by kovzol** [comment]
Very nice improvement, thanks! Please show an error message if the loaded image does not contain any xpf data. Is the hidden temp file working also on non-Unix systems?

**Comment by kanurag94** [comment]
Yes this works in non unix systems as well.
>  Please show an error message if the loaded image does not contain any xpf data.
Done.

**Comment by kovzol** [comment]
It seems to me that the error message is shown for a very short time. Can this be improved?

**Comment by kanurag94** [comment]
This is being handled by xaos timer library. Currently they are visible for same time as other error messages.
We can change the timers esp. EXPIRETIME macro

**Comment by kovzol** [comment]
OK, great. Can it be risky to increase EXPIRETIME? Does it have a negative effect somewhere else?

**Comment by kanurag94** [comment]
Setting it from 4000000 to 5000000 looks better without negative effects.

**Pull request merged**
