### PR TITLE
Added logarithmic smooth colorizing 

### PR DESCRIPTION
**Pull request by iaoesch**
Added a new smooth colorizing method, using logarithmic value, gives smoother color gradient in chaotic places.
(New Menupoint 'Fractal/outcoloring mode/smooth log'

Also replaced outcoloer mode constants with enum s

Tested on osx with Qt7.1

### CODE REVIEW

**Comment by kovzol** [comment]
Nice feature, thank you! Maybe you want to explain it by extending the tutorial text for outcoloring modes, see https://github.com/xaos-project/XaoS/wiki#out-coloring-modes for more information.

**Comment by iaoesch** [comment]
Additionally, the Table with the outcolor modes in the Wiki at 
https://github.com/xaos-project/XaoS/wiki/Reference#outside-coloring-mode
needs to be updated: Adding Smooth color and updating the number for true-color.
(That seems not to be possible by mergerequest...)

**Comment by kovzol** [comment]
Thanks! I'll check it out soon and give you feedback.

**Comment by kovzol** [comment]
I made some minor improvements: https://github.com/xaos-project/XaoS/commit/776621208f4bdd24d025fcb527c9e86b8d82fc52 (I lowercased newton and magnet, they look more uniform this way).

Please consider giving your full name and an email address to see full credits on your work.

Also, please indicate what exactly we should add in the wiki to describe the new feature. Thanks!

**Pull request merged**
