### PR TITLE
Improve Rendering

### PR DESCRIPTION
**Pull request by kanurag94**
After #184 , there were some changes regarding batch rendering

> The patch basically works well, but I found the following issues:
> It seems that displayed messages can be mixed between animations.
> The naming would be better to be related with the original filenames and not the selection number.
> If this patch works correctly, we no longer need the Render... menu. But instead of removing it, I suggest we use the Render... menu and allow selection of multiple files in that menu.

These are addressed in this PR

### CODE REVIEW

**Comment by kovzol** [comment]
I like this new version. However I am unsure what the correct way would be to define the filenames.
Now it is something like anim_%s_%06d.png where anim is the basename, %s is the filename (without extension) and %06d is the frame number, padded to 6 digits. Maybe our users want to set this on their own.
Other software tools have similar traditions, see e.g. https://stackoverflow.com/questions/10957412/fastest-way-to-extract-frames-using-ffmpeg, for example ffmpeg allows defining the pattern with something like `$filename%03d.bmp`.
Let's discuss this question here.

**Comment by kanurag94** [comment]
I think it's a good idea to let users define their own pattern for file generation. However letting the user define %06d part is not foolproof. For a new user it's difficult to know how many frames their animation file might take.
The rendered images could be overwritten if a user provides a pattern without filename. A pattern like ```basename_%s_%xD.png``` where %s is the filename and x is user definable could be a better alternative. I would like the basename functionality to remain since I might be tagging the rendered images by my own signature for example march_dragon_01.png

**Comment by kovzol** [comment]
Yes, we must be careful here. Our users include non-experts. But we can, of course, add a Help button here, and define a good default entry.
For the moment the current behavior is acceptable. Maybe for a future version someday we will have a good idea for an improvement.
In fact, if a user selects fract1.xpf and fract1.xaf, the result is something mixed. Maybe we still want to keep the extension in the filenames in some form...

**Comment by kanurag94** [comment]
> In fact, if a user selects fract1.xpf and fract1.xaf, the result is something mixed. Maybe we still want to keep the extension in the filenames in some form...
Yes and some of the users may name their file with common names for example "untitled.xpf" again and again and end up overwriting their previously rendered images. This is problematic. That's why I was previously using filenumber in #184 but that is still not enough. We need to give some warning when this occurs.

**Pull request merged**
